import * as Blockly from "blockly/core";
import { Order } from "blockly/javascript";

export const CurrencyCode = [
  ["AED", "aed"],
  ["AFA", "afa"],
  ["ALL", "all"],
  ["AMD", "amd"],
  ["ANG", "ang"],
  ["AOA", "aoa"],
  ["ARS", "ars"],
  ["AUD", "aud"],
  ["AWG", "awg"],
  ["AZM", "azm"],
  ["BAM", "bam"],
  ["BBD", "bbd"],
  ["BDT", "bdt"],
  ["BGN", "bgn"],
  ["BHD", "bhd"],
  ["BIF", "bif"],
  ["BMD", "bmd"],
  ["BND", "bnd"],
  ["BOB", "bob"],
  ["BRL", "brl"],
  ["BSD", "bsd"],
  ["BTN", "btn"],
  ["BWP", "bwp"],
  ["BYR", "byr"],
  ["BZD", "bzd"],
  ["CAD", "cad"],
  ["CDF", "cdf"],
  ["CHF", "chf"],
  ["CLP", "clp"],
  ["CNY", "cny"],
  ["COP", "cop"],
  ["CRC", "crc"],
  ["CSD", "csd"],
  ["CUP", "cup"],
  ["CVE", "cve"],
  ["CYP", "cyp"],
  ["CZK", "czk"],
  ["DJF", "djf"],
  ["DKK", "dkk"],
  ["DOP", "dop"],
  ["DZD", "dzd"],
  ["EEK", "eek"],
  ["EGP", "egp"],
  ["ERN", "ern"],
  ["ETB", "etb"],
  ["EUR", "eur"],
  ["FJD", "fjd"],
  ["FKP", "fkp"],
  ["GBP", "gbp"],
  ["GEL", "gel"],
  ["GGP", "ggp"],
  ["GHC", "ghc"],
  ["GIP", "gip"],
  ["GMD", "gmd"],
  ["GNF", "gnf"],
  ["GTQ", "gtq"],
  ["GYD", "gyd"],
  ["HKD", "hkd"],
  ["HNL", "hnl"],
  ["HRK", "hrk"],
  ["HTG", "htg"],
  ["HUF", "huf"],
  ["IDR", "idr"],
  ["ILS", "ils"],
  ["IMP", "imp"],
  ["INR", "inr"],
  ["IQD", "iqd"],
  ["IRR", "irr"],
  ["ISK", "isk"],
  ["JEP", "jep"],
  ["JMD", "jmd"],
  ["JOD", "jod"],
  ["JPY", "jpy"],
  ["KES", "kes"],
  ["KGS", "kgs"],
  ["KHR", "khr"],
  ["KMF", "kmf"],
  ["KPW", "kpw"],
  ["KRW", "krw"],
  ["KWD", "kwd"],
  ["KYD", "kyd"],
  ["KZT", "kzt"],
  ["LAK", "lak"],
  ["LBP", "lbp"],
  ["LKR", "lkr"],
  ["LRD", "lrd"],
  ["LSL", "lsl"],
  ["LTL", "ltl"],
  ["LVL", "lvl"],
  ["LYD", "lyd"],
  ["MAD", "mad"],
  ["MDL", "mdl"],
  ["MGA", "mga"],
  ["MKD", "mkd"],
  ["MMK", "mmk"],
  ["MNT", "mnt"],
  ["MOP", "mop"],
  ["MRO", "mro"],
  ["MTL", "mtl"],
  ["MUR", "mur"],
  ["MVR", "mvr"],
  ["MWK", "mwk"],
  ["MXN", "mxn"],
  ["MYR", "myr"],
  ["MZM", "mzm"],
  ["NAD", "nad"],
  ["NGN", "ngn"],
  ["NIO", "nio"],
  ["NOK", "nok"],
  ["NPR", "npr"],
  ["NZD", "nzd"],
  ["OMR", "omr"],
  ["PAB", "pab"],
  ["PEN", "pen"],
  ["PGK", "pgk"],
  ["PHP", "php"],
  ["PKR", "pkr"],
  ["PLN", "pln"],
  ["PYG", "pyg"],
  ["QAR", "qar"],
  ["ROL", "rol"],
  ["RUB", "rub"],
  ["RWF", "rwf"],
  ["SAR", "sar"],
  ["SBD", "sbd"],
  ["SCR", "scr"],
  ["SDD", "sdd"],
  ["SEK", "sek"],
  ["SGD", "sgd"],
  ["SHP", "shp"],
  ["SIT", "sit"],
  ["SKK", "skk"],
  ["SLL", "sll"],
  ["SOS", "sos"],
  ["SPL", "spl"],
  ["SRD", "srd"],
  ["STD", "std"],
  ["SVC", "svc"],
  ["SYP", "syp"],
  ["SZL", "szl"],
  ["THB", "thb"],
  ["TJS", "tjs"],
  ["TMM", "tmm"],
  ["TND", "tnd"],
  ["TOP", "top"],
  ["TRL", "trl"],
  ["TRY", "try"],
  ["TTD", "ttd"],
  ["TVD", "tvd"],
  ["TWD", "twd"],
  ["TZS", "tzs"],
  ["UAH", "uah"],
  ["UGX", "ugx"],
  ["USD", "usd"],
  ["UYU", "uyu"],
  ["UZS", "uzs"],
  ["VEB", "veb"],
  ["VND", "vnd"],
  ["VUV", "vuv"],
  ["WST", "wst"],
  ["XAF", "xaf"],
  ["XAG", "xag"],
  ["XAU", "xau"],
  ["XCD", "xcd"],
  ["XDR", "xdr"],
  ["XOF", "xof"],
  ["XPD", "xpd"],
  ["XPF", "xpf"],
  ["XPT", "xpt"],
  ["YER", "yer"],
  ["ZAR", "zar"],
  ["ZMK", "zmk"],
  ["ZWD", "zwd"],
  // Unknown handler
  ["ZZZ", "zzz"],
];

export const currencyNameMap = {
  aed: "United Arab Emirates, Dirhams",
  afa: "Afghanistan, Afghanis",
  all: "Albania, Leke",
  amd: "Armenia, Drams",
  ang: "Netherlands Antilles, Guilders (Florins)",
  aoa: "Angola, Kwanza",
  ars: "Argentina, Pesos",
  aud: "Australia, Dollars",
  awg: "Aruba, Guilders (Florins)",
  azm: "Azerbaijan, Manats",
  bam: "Bosnia and Herzegovina, Convertible Marka",
  bbd: "Barbados, Dollars",
  bdt: "Bangladesh, Taka",
  bgn: "Bulgaria, Leva",
  bhd: "Bahrain, Dinars",
  bif: "Burundi, Francs",
  bmd: "Bermuda, Dollars",
  bnd: "Brunei Darussalam, Dollars",
  bob: "Bolivia, Bolivianos",
  brl: "Brazil, Brazil Real",
  bsd: "Bahamas, Dollars",
  btn: "Bhutan, Ngultrum",
  bwp: "Botswana, Pulas",
  byr: "Belarus, Rubles",
  bzd: "Belize, Dollars",
  cad: "Canada, Dollars",
  cdf: "Congo/Kinshasa, Congolese Francs",
  chf: "Switzerland, Francs",
  clp: "Chile, Pesos",
  cny: "China, Yuan Renminbi",
  cop: "Colombia, Pesos",
  crc: "Costa Rica, Colones",
  csd: "Serbia, Dinars",
  cup: "Cuba, Pesos",
  cve: "Cape Verde, Escudos",
  cyp: "Cyprus, Pounds",
  czk: "Czech Republic, Koruny",
  djf: "Djibouti, Francs",
  dkk: "Denmark, Kroner",
  dop: "Dominican Republic, Pesos",
  dzd: "Algeria, Algeria Dinars",
  eek: "Estonia, Krooni",
  egp: "Egypt, Pounds",
  ern: "Eritrea, Nakfa",
  etb: "Ethiopia, Birr",
  eur: "Euro Member Countries, Euro",
  fjd: "Fiji, Dollars",
  fkp: "Falkland Islands (Malvinas), Pounds",
  gbp: "United Kingdom, Pounds",
  gel: "Georgia, Lari",
  ggp: "Guernsey, Pounds",
  ghc: "Ghana, Cedis",
  gip: "Gibraltar, Pounds",
  gmd: "Gambia, Dalasi",
  gnf: "Guinea, Francs",
  gtq: "Guatemala, Quetzales",
  gyd: "Guyana, Dollars",
  hkd: "Hong Kong, Dollars",
  hnl: "Honduras, Lempiras",
  hrk: "Croatia, Kuna",
  htg: "Haiti, Gourdes",
  huf: "Hungary, Forint",
  idr: "Indonesia, Rupiahs",
  ils: "Israel, New Shekels",
  imp: "Isle of Man, Pounds",
  inr: "India, Rupees",
  iqd: "Iraq, Dinars",
  irr: "Iran, Rials",
  isk: "Iceland, Kronur",
  jep: "Jersey, Pounds",
  jmd: "Jamaica, Dollars",
  jod: "Jordan, Dinars",
  jpy: "Japan, Yen",
  kes: "Kenya, Shillings",
  kgs: "Kyrgyzstan, Soms",
  khr: "Cambodia, Riels",
  kmf: "Comoros, Francs",
  kpw: "Korea (North), Won",
  krw: "Korea (South), Won",
  kwd: "Kuwait, Dinars",
  kyd: "Cayman Islands, Dollars",
  kzt: "Kazakhstan, Tenge",
  lak: "Laos, Kips",
  lbp: "Lebanon, Pounds",
  lkr: "Sri Lanka, Rupees",
  lrd: "Liberia, Dollars",
  lsl: "Lesotho, Maloti",
  ltl: "Lithuania, Litai",
  lvl: "Latvia, Lati",
  lyd: "Libya, Dinars",
  mad: "Morocco, Dirhams",
  mdl: "Moldova, Lei",
  mga: "Madagascar, Ariary",
  mkd: "Macedonia, Denars",
  mmk: "Myanmar (Burma), Kyats",
  mnt: "Mongolia, Tugriks",
  mop: "Macau, Patacas",
  mro: "Mauritania, Ouguiyas",
  mtl: "Malta, Liri",
  mur: "Mauritius, Rupees",
  mvr: "Maldives (Maldive Islands), Rufiyaa",
  mwk: "Malawi, Kwachas",
  mxn: "Mexico, Pesos",
  myr: "Malaysia, Ringgits",
  mzm: "Mozambique, Meticais",
  nad: "Namibia, Dollars",
  ngn: "Nigeria, Nairas",
  nio: "Nicaragua, Cordobas",
  nok: "Norway, Krone",
  npr: "Nepal, Nepal Rupees",
  nzd: "New Zealand, Dollars",
  omr: "Oman, Rials",
  pab: "Panama, Balboa",
  pen: "Peru, Nuevos Soles",
  pgk: "Papua New Guinea, Kina",
  php: "Philippines, Pesos",
  pkr: "Pakistan, Rupees",
  pln: "Poland, Zlotych",
  pyg: "Paraguay, Guarani",
  qar: "Qatar, Rials",
  rol: "Romania, Lei",
  rub: "Russia, Rubles",
  rwf: "Rwanda, Rwanda Francs",
  sar: "Saudi Arabia, Riyals",
  sbd: "Solomon Islands, Dollars",
  scr: "Seychelles, Rupees",
  sdd: "Sudan, Dinars",
  sek: "Sweden, Kronor",
  sgd: "Singapore, Dollars",
  shp: "Saint Helena, Pounds",
  sit: "Slovenia, Tolars",
  skk: "Slovakia, Koruny",
  sll: "Sierra Leone, Leones",
  sos: "Somalia, Shillings",
  spl: "Seborga, Luigini",
  srd: "Suriname, Dollars",
  std: "São Tome and Principe, Dobras",
  svc: "El Salvador, Colones",
  syp: "Syria, Pounds",
  szl: "Swaziland, Emalangeni",
  thb: "Thailand, Baht",
  tjs: "Tajikistan, Somoni",
  tmm: "Turkmenistan, Manats",
  tnd: "Tunisia, Dinars",
  top: "Tonga, Pa’anga",
  trl: "Turkey, Liras (obsolete)",
  try: "Turkey, New Lira",
  ttd: "Trinidad and Tobago, Dollars",
  tvd: "Tuvalu, Tuvalu Dollars",
  twd: "Taiwan, New Dollars",
  tzs: "Tanzania, Shillings",
  uah: "Ukraine, Hryvnia",
  ugx: "Uganda, Shillings",
  usd: "United States of America, Dollars",
  uyu: "Uruguay, Pesos",
  uzs: "Uzbekistan, Sums",
  veb: "Venezuela, Bolivares",
  vnd: "Viet Nam, Dong",
  vuv: "Vanuatu, Vatu",
  wst: "Samoa, Tala",
  xaf: "Communauté Financière Africaine, Francs",
  xag: "Silver, Ounces",
  xau: "Gold, Ounces",
  xcd: "East Caribbean Dollars",
  xdr: "International Monetary Fund (IMF) Special Drawing Rights",
  xof: "Communauté Financière Africaine, Francs",
  xpd: "Palladium Ounces",
  xpf: "Comptoirs Français du Pacifique Francs",
  xpt: "Platinum, Ounces",
  yer: "Yemen, Rials",
  zar: "South Africa, Rand",
  zmk: "Zambia, Kwacha",
  zwd: "Zimbabwe, Zimbabwe Dollars",
  // Unknown handler
  zzz: "Unknown Currency",
};

export const investecCurrenciesBlock = {
  type: "investec_currencies",
  message0: "currency: %1",
  args0: [
    {
      type: "field_dropdown",
      name: "CURRENCY",
      options: CurrencyCode,
    },
  ],
  output: "String",
  colour: 230,
};

export function installCurrenciesBlock(generators = {}) {
  Blockly.defineBlocksWithJsonArray([investecCurrenciesBlock]);
  if (generators.javascript) {
    generators.javascript.forBlock["investec_currencies"] = currenciesGenerator;
    // generators.javascript.addReservedWords("specialReservedWord");
  }
}

const currenciesGenerator = function (block) {
  var mode = block.getFieldValue("CURRENCY");
  return [`'${mode}'`, Order.ATOMIC]; // Simplified returns as well.
};
